# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  format_listener:

    rules:
      prefer_extension: false
      fallback_format: json

  view:
    view_response_listener:  true

  body_converter:
    enabled: true
    validate: true
